### ISSUE TITLE
Is there an executable file where I can run it?

### ISSUE THREAD

**Issue by OPEN1004MIND** [VladimirMakeev/D2RSG#2]
I came across this site by accident.
As a Disciples-loving gamer, this is a welcome source of information.
I don't know the program.
I'm asking because I don't know how I can get this program running.
Is there an executable file where I can run it?

**Comment by VladimirMakeev** [comment]
Hi! This is a repository of random map generator for Disciples 2.
It is possible to use the program directly: download the repo and open it in Microsoft Visual Studio, build `MapGeneratorTest` project and you will get the console application which can generate random maps if you specify game folder as well as map template.
But the easiest way to try it is to download one of the mods for the game: [sMNS](https://norvezskayasemga.pro/mods/19) and [Motlin's mod](https://norvezskayasemga.pro/mods/24) being the two main examples.
These mods have map generator integrated into the game, you'll just need to open new menu before starting new map and choose map template.

**Comment by OPEN1004MIND** [comment]
> Hi! This is a repository of random map generator for Disciples 2. It is possible to use the program directly: download the repo and open it in Microsoft Visual Studio, build `MapGeneratorTest` project and you will get the console application which can generate random maps if you specify game folder as well as map template. But the easiest way to try it is to download one of the mods for the game: [sMNS](https://norvezskayasemga.pro/mods/19) and [Motlin's mod](https://norvezskayasemga.pro/mods/24) being the two main examples. These mods have map generator integrated into the game, you'll just need to open new menu before starting new map and choose map template.

Thank you for your response.
I'm not a developer, so it seems difficult to use MVS even if I don't have any development tools.
Could you please create an executable and distribute it?
I would be grateful if you could distribute the executable file.

**Comment by VladimirMakeev** [comment]
If you just want to generate map from template and play it in the game - the easiest way is to download one of the mods that already have map generator feature. You will find a new 'random scenario' game menu.
If you want to develop the generator itself - you will need development tools.
I can't think of any useful case where standalone generator executable file will be helpful. If you want to look at map or play it - you still need the game. If you are tinkering with generation algorithms - you need dev. tools.

Sorry, but I'm not going to spend my time at this task. It is better to work on generator itself. My ultimate goal has always been seamless integration with the game.
